include:
 - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml
 - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/pipeline-jobs.yml

# Fails to reproduce libapache2-mod-apparmor
reprotest:
  allow_failure: true

variables:
  SALSA_CI_REPROTEST_ENABLE_DIFFOSCOPE: 1
